### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by romanlevashov** [sanPuerquitoProgramador/next-and-prev-post#1]
Hello! I'm trying to use your plugin for the previous and next pages, but it gives me an error: 

**"count(): Parameter must be an array or an object that implements Countable"**

I installed the RainLab Blog and Twig Extensions plugins and include the component ( {% component 'nextAndPrev' %} ) in my post page but its doesnt works.
I have only one assumption that the problem can be in the version of PHP, I have 7.2 What would you advise me to try?

Thanks!

**Comment by sanPuerquitoProgramador** [comment]
Hi! thanks for reporting this bug. It has been resolved. The updated version has been sent to October Market, it takes a few minutes to be available for all.
Nice day!

**Comment by romanlevashov** [comment]
Thank you! it's works!
